---
format:
  html:
    page-layout: full
execute:
    echo: false
---

# R Session 01 

```{ojs}
//| panel: input
viewof beta = Inputs.range(
  [0.0, 2.0],
  {value: 0.3, step: 0.01, label: "Transmission rate"}
)
viewof dur_inf = Inputs.range(
  [0.0, 20],
  {value: 6.0, step: 0.5, label: "Duration of Infection (days)"}
)

viewof I0 = Inputs.range(
  [0.0, 1.0],
  {value: 0.01, step: 0.01, label: "Initial fraction infected"}
)

viewof area = Inputs.toggle(
  {label: "Cumulative Area plot", value: false}
)
```

```{ojs}
function sir(dydt, y, t) {
  var gamma = 1 / dur_inf

  dydt[0] = -beta * y[0] * y[1]
  dydt[1] = beta * y[0] * y[1] - gamma * y[1]
  dydt[2] = gamma * y[1]
}
```

```{ojs}
import {odeRK4} from '@rreusser/integration@3064'
import { aq, op } from '@uwdata/arquero'
```

```{ojs}
function simulate(f, t0, y0, dt, tmax) {
  var t = t0
  var y = y0
  var i = 0

  var tsim = [t0]
  var ysim = [y0]

  for (t = t0 + dt; t <= tmax; t += dt) {
    ysim.push(odeRK4([], ysim[i], f, dt))
    tsim.push(t)
    i += 1
  }
  
  return aq.table({
    t: tsim,
    S: ysim.map(d => d[0]),
    I: ysim.map(d => d[1]),
    R: ysim.map(d => d[2])
    })
}
```

```{ojs}
sir_sol = simulate(sir, 0, [1.0-I0, I0, 0.0], 0.01, 200)
sir_sol_long = sir_sol.fold(aq.not('t'), {as: ['State', 'Fraction']})
```

```{ojs}
SIRcolors = ["#1f77b4", "#ff7f0e", "#FF3851"]
```

::: {.panel-tabset}

## Closed Population

```{ojs}
closed_R0 = beta * dur_inf
closed_R0_str = closed_R0.toLocaleString(undefined, {minimumFractionDigits: 2})

finalsize = sir_sol.get("R", sir_sol.numRows()-1)
finalsize_str = finalsize.toLocaleString(undefined, {minimumFractionDigits: 2})

md`${tex`R_0 = ${closed_R0_str}`}`
md`${tex`\text{Final size} = ${finalsize_str}`}`
```

```{ojs}
Plot.plot({
  color: {
    legend: true,
    domain: ["S", "I", "R"],
    range: SIRcolors
  },
  style: {fontSize: "20px"},
  marginLeft: 65,
  marginTop: 40,
  grid: true,
  width: 1000,
  height: 600,
  y: {domain: [0, 1]},
  marks: [
    area ?
      Plot.areaY(sir_sol_long, {x: "t", y: "Fraction", fill: "State"}) :
      Plot.lineY(sir_sol_long, {x: "t", y: "Fraction", stroke: "State", strokeWidth: 6})
  ]
})
```

## Demographics

```{ojs}
//| panel: input
viewof births = Inputs.range(
  [0.0, 0.5],
  {value: 0.05, step: 0.001, label: "Birth rate"}
)

viewof tmax = Inputs.range(
  [200.0, 500.0],
  {value: 200.0, step: 50.0, label: "Maximum simulation time"}
)
```

```{ojs}
demographic_R0 = beta / ((1/dur_inf) + births)
eq_S = 1 / demographic_R0
eq_I = births / beta * (demographic_R0 - 1)
eq_R = 1 - (eq_S + eq_I)

eq_vals = aq.table({
  State: ["S", "I", "R"],
  Fraction: [eq_S, eq_I, eq_R]
})

demographic_R0_str = demographic_R0.toLocaleString(undefined, {minimumFractionDigits: 2})

md`${tex`R_0 = ${demographic_R0_str}`}`
```

```{ojs}
function sir_demographic(dydt, y, t) {
  var gamma = 1 / dur_inf

  dydt[0] = - beta * y[0] * y[1] + births * (1 - y[0])
  dydt[1] = beta * y[0] * y[1] - gamma * y[1] - births * y[1]
  dydt[2] = gamma * y[1] - births * y[2]
}
```

```{ojs}
sir_demographic_sol = simulate(sir_demographic, 0, [1.0-I0, I0, 0.0], 0.01, tmax)
sir_demographic_sol_long = sir_demographic_sol.fold(aq.not('t'), {as: ['State', 'Fraction']})
```

```{ojs}
Plot.plot({
  color: {
    legend: true,
    domain: ["S", "I", "R"],
    range: SIRcolors
  },
  style: {fontSize: "20px"},
  marginLeft: 65,
  marginTop: 40,
  grid: true,
  width: 1000,
  height: 600,
  y: {domain: [0, 1]},
  marks: [
    area ?
      Plot.areaY(sir_demographic_sol_long, {x: "t", y: "Fraction", fill: "State"}) :
      [
        demographic_R0 >= 1.0 ?
          Plot.ruleY(
            eq_vals,
            {y: "Fraction", stroke: "State", strokeWidth: 2, strokeDasharray: [10]}
          ) :
          null,
        Plot.lineY(
          sir_demographic_sol_long,
          {x: "t", y: "Fraction", stroke: "State", strokeWidth: 6}
        )
      ]
  ]
})
```

:::

## Exercise 1
### Closed Population Model

::: {.callout-instructions}
**SET**

Transmission rate = 1

Duration of infection = 4.
:::

#### What is $R_0$? {#sec-whatisr0}
#### What is epidemic final size?
#### Does this make sense given our definition of $R_0$?

::: {.callout-instructions}
Toggle on the cumulative area button and see what the epidemic final size is (approximately)
:::

#### At approximately what time does the epidemic end?

::: {.callout-instructions}
**SET**

Duration of infection = 8 days

Transmission rate so you get the same $R_0$ in @sec-whatisr0
:::

#### How does the epidemic final size compare?
#### At what time (approx) does the epidemic end?

::: {.callout-note}
Size is determined by $R_0$, duration is determined by recovery rate $\left(\gamma = \frac{1}{\text{duration of infection}}\right)$
:::

Now, imagine that we have a drug (or vaccine) available to everyone that either reduced transmission OR shortened the duration of infection.

::: {.callout-instructions}
**SET**

Transmission rate = 1

Duration of infection = 8 days
:::

#### Note the epidemic final size and the time until the epidemic is over.

::: {.callout-instructions}
Now, imagine everyone has access to the drug (unrealistic) that reduces transmission by $P \%$
:::

#### What happens to the final size and outbreak duration?

Now, imagine everyone has access to a drug that reduces the duration of infection from 8 to 2 days (75% reduction).

#### What happens to the final size and outbreak duration?

::: {.callout-question}
Which would you prefer and why? (This is the only really open ended question, but should be pretty straightforward discussion)
:::

### Demographic Model

::: {.callout-instructions}
**SET:**
Transmission = 1

Duration = 8

Birth rate = .002
:::

#### What is $R_0$? {#sec-demog-whatisr0}
#### What is the equilibrium proportion that is susceptible?
#### If you were to test for antibodies against infection in the population, what proportion would you expect to be positive?

::: {.callout-note}
Assume a perfectly accurate serological test
:::

#### At what time (approximately) does the system reach equilibrium?

::: {.callout-instructions}
**SET**

Birth rate = 0.005
:::

#### What is the new $R_0$? {#sec-demog-updatedr0}
#### At what time (approximately) does the system reach equilibrium?

::: {.callout-instructions}
Transmission rate so you get the same $R_0$ in @sec-demog-whatisr0
:::

#### What is the new equilibrium proportion that is susceptible?
#### What is different about the prevalence of infection (equilibrium proportion that is infected) in the scenarios @sec-demog-whatisr0 and @sec-demog-updatedr0 i.e. higher birth rate with the same $R_0$?

## Matt Comments

### Exercise 1:
#### Code for closed population

<!-- 1. Set transmission rate to 1 and duration of infection to 4.
   1. what is R0? what is epidemic final size? Does this make sense given our definition of R0?
   2. toggle on the cumulative area button and see what the epidemic final size is (approximately)
      1. At approximately what time does the epidemic end?
      2. Now change the duration of infection to 2*84= 8 days and change the transmission rate so you get the same R0. How does the epidemic final size compare? At what time (approx) does the epidemic end? (Size is determined by R0, duration is determined by gamma) -->

<!-- 2. Now, imagine that we have a drug (or vaccine) available to everyone that either reduced transmission OR shortened the duration of infection.
   1. Set transmission to 1 and duration to 8 days. Note the epidemic final size and the time until the epidemic is over. Now, imagine everyone has access to the drug (unrealistic) that reduces transmission by P%, what happens to final size and outbreak duration? (e.g. transmission =1 and duration =8; reduce transmission by .75 and go from final size of 1 to final size of .8. duration from 50 to 100.)
3. Now, imagine everyone has access to a drug that reduces the duration of infection from 8 to 2 days (75% reduction), what happens to final size and outbreak duration? (e.g. transmission =1 and duration =8; reduce transmission by .75 and go from final size of 1 to final size of .8. duration from 50 to 25.)

Which would you prefer and why? (This is the only really open ended question, but should be pretty straightforward discussion) -->

#### Code with demography (need to do post-session review)



1. What is R0?
2. What is equilibrium proportion that is susceptible? If you were to test for antibodies against infection in the population, what proportion would you expect to be positive?
3. At what time (approximately) does the system reach equilibrium?
4. Change the birth rate to 0.005 — what is the new R0? At what time (approximately) does the system reach equilibrium?
5. Change the transmission rate to get (approximately) the same R0 as in 1B.1. What is the equilibrium proportion that are susceptible?
6. What is different about the prevalence of infection (the equilibrium proportion that are infected in the scenarios in 1B.1 and 1B.4 (higher birth rate with same R0 has higher prevalence)

### Exercise 2: Review and annotate code in R

(We could give them the annotations and have them place them on the code)
