---
author: ""
---

# Workshop Schedule {.unnumbered}

|Instructors | Emails |
|:--|:--|
| Micaela E. Martinez (WE ACT for Environmental Justice) | micaela *dot* martinez *at* weact *dot* org |
| Matt Ferrari (Penn State University) | mjf283 *at* psu *dot* edu |
| **TA**: Callum Arnold (Penn State University) | cfa5228 *at* psu *dot* edu |

: {.striped .hover tbl-colwidths="[60,40]"}

**General workshop times**:

July 10, Monday: 8:30 a.m. - 5 p.m. PST

July 12, Tuesday: 8:30 a.m. - 5 p.m. PST

July 13, Wednesday: 8:30 a.m. - 12 p.m. PST

::: {.callout-important}
All times are in local time PST
:::

## Before class

Please see pre-requisites on the course website

## Day 01 – Monday 

| Time | Section |
|:--|:--|
| 8:30 - 9:30am | Lecture 1: Intro to Modeling by Micaela Martinez |
| 9:30 - 10am | Lecture 2: Basics of SIR Models by Matt Ferrari (first half) |
| 10 - 10:30pm | coffee break |
| 10:30am - 11am | Lecture 2: Basics of SIR Models by Matt Ferrari (second half) |
| 11 - 12pm | `R` Session 1: Intro to modeling by Callum Arnold |
| 12 - 1:30pm | lunch on your own |
| 1:30pm - 2pm | `R` Session 1: Intro to modeling (continued) by Callum Arnold |
| 2pm - 3pm | Lecture 3: Vaccination & Interventions by Micaela Martinez |
| 3 - 4:15pm | Finish `R` exercises and work on [group assignment](#group-assignments) for `R` Session 1. |
| 4:15pm - 5pm | Group Assignment debrief for `R` Session 1 |

: {.striped .hover tbl-colwidths="[25,75]"}


## Day 02 – Tuesday

| Time | Section |
|:--|:--|
| 8:30am - 9:30am | Lecture 4: Heterogeneity in Models by Callum Arnold |
| 9:30 - 10am | Lecture 5: Heterogeneity expanded (age structure and the force of infection) by Matt Ferrari (first half) |
| 10 - 10:30am | Coffee Break |
| 10:30am - 11am | Lecture 5: Heterogeneity expanded (age structure and the force of infection) by Matt Ferrari (second half) |
| 11 - 12am | `R` Session 2: Heterogeneity and age structure by Callum Arnold |
| 12 - 1:30pm | lunch on your own |
| 1:30 - 2:30pm | Lecture 6: Parameter Estimation (estimating $R_0$) by Matt Ferrari |
| 2:30 - 3:30pm | `R` Session 3: Parameter estimation by Callum Arnold |
| 3:30pm - 4:15pm | Finish `R` exercises from the day and work on [group assignment](#group-assignments) for `R` Sessions 2 and 3 |
| 4:15pm - 5pm | Group Assignment debrief for `R` Session 2 |

: {.striped .hover tbl-colwidths="[25,75]"}

## Day 03 – Wednesday

| Time | Section |
|:--|:--|
| 8:30am - 9:30am | Lecture 7: Confronting models with data by Micaela Martinez |
| 9:30am - 10am | Lecture 8: Stochasticity and Uncertainty lecture by Micaela Martinez and Matt Ferrari (first half) |
| 10am - 10:30am | Coffee break |
| 10:30am - 11am | Lecture 8: Stochasticity and Uncertainty lecture by Micaela Martinez and Matt Ferrari (first half) |
| 11am - 12am | Group Assignment debrief for `R` Session 3 and any other discussion points |

: {.striped .hover tbl-colwidths="[25,75]"}

**Class Ends Noon on Wednesday**

## Group assignments
- Each individual should create a slide deck to address each of the following questions for each of the day’s `R` exercises.
- Each group should develop consensus slides to present when we come together as a class.
- Groups will be asked to share their intuition gained.

**Questions**:

1. What were the top two take-away messages you gained from this `R` exercise?
2. What was the most unexpected/non-intuitive thing you learned from this `R` exercise?
